;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;      ____        __      __              
;;     / __ \____  / /_  __/ /_  ____ ______
;;    / /_/ / __ \/ / / / / __ \/ __ `/ ___/
;;   / ____/ /_/ / / /_/ / /_/ / /_/ / /    
;;  /_/    \____/_/\__, /_.___/\__,_/_/     
;;                /____/                    
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Global WM Settings

[global/wm]
margin-bottom = 0
margin-top = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; File Inclusion
include-file = ~/.config/polybar/colors.ini

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Bar Settings

[bar/main]
monitor =
monitor-fallback =
monitor-strict = false
bottom = true
fixed-center = true
width = 17%
height = 60
offset-x = 20
offset-y = 20
background = ${color.bg}
foreground = ${color.fg}
radius-top = 10.0
radius-bottom = 10.0
line-size = 2
line-color = ${color.ac}
border-bottom-size = 0
border-color = ${color.ac}
padding = 2
module-margin-left = 1
module-margin-right = 1

; Fuentes (Agregamos la Hack Nerd Font que instalamos con el script)
font-0 = "Hack Nerd Font:style=Regular:size=10;3"
font-1 = "Hack Nerd Font:style=Bold:size=24;2"
font-2 = "Hack Nerd Font:style=Regular:size=22;6"
font-3 = "Source Code Pro:size=10;3"
font-4 = "Montserrat Medium:style=Medium:size=12;3"
font-5 = "Helvetica Rounded:style=Bold:size=10.5;3"
font-6 = "Hurmit Nerd Font Mono:style=medium:pixelsize=17;3"
font-7 = "Hack Nerd Font Mono:size=23;6"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/primary]
inherit = bar/main
offset-x = 96.9%
offset-y = 15
width = 2.5%
height = 40
bottom = false
padding = 0
module-margin-left = 0
module-margin-right = 0
background = ${color.bg}
foreground = #44abff
modules-center = sysmenu
wm-restack = bspwm

[bar/secondary]
inherit = bar/main
width = 7%
height = 40
offset-x = 3.8%
offset-y = 15
background = ${color.bg}
foreground = ${color.white}
bottom = false
padding = 1
module-margin-left = 0
module-margin-right = 0
modules-center = date 
wm-restack = bspwm

[bar/target]
inherit = bar/main
width = 19%
height = 40
offset-x = 77%
offset-y = 15
background = ${color.bg}
foreground = ${color.white}
bottom = false
padding = 1
module-margin-left = 0
module-margin-right = 0
modules-center = target_status
wm-restack = bspwm

[bar/ethernet_bar]
inherit = bar/main
width = 15%
height = 40
offset-x = 3.8%
offset-y = 15
background = ${color.bg}
foreground = ${color.white}
bottom = false
padding = 1
module-margin-left = 0
module-margin-right = 0
modules-center = ethernet_status
wm-restack = bspwm

[bar/vpn_bar]
inherit = bar/main
width = 15%
height = 40
offset-x = 19.3%
offset-y = 15
background = ${color.bg}
foreground = ${color.white}
bottom = false
padding = 1
module-margin-left = 0
module-margin-right = 0
modules-center = vpn_status
wm-restack = bspwm

[bar/log]
inherit = bar/main
width = 2.5%
height = 40
offset-x = 1%
offset-y = 15
bottom = false
foreground = ${color.white}
background = #80bfff
padding = 0
modules-center = my-text-label
wm-restack = bspwm

[bar/top]
inherit = bar/main
width = 6%
height = 40
offset-x = 90.5%
offset-y = 15
bottom = false
font-0 = "Hack Nerd Font:size=12;3"
background = ${color.bg}
padding = 1
module-margin-left = 1
module-margin-right = 1
modules-center = alsa battery network

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

separator =
spacing = 0
dim-value = 1.0
wm-name = openbox
locale = 
tray-position = none
tray-detached = false
tray-maxsize = 16
tray-transparent = false
tray-background = ${color.bg}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0
wm-restack = bspwm
enable-ipc = true

click-left = 
click-middle = 
click-right =
scroll-up =
scroll-down =
double-click-left =
double-click-middle =
double-click-right =
cursor-click = 
cursor-scroll = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[settings]
throttle-output = 5
throttle-output-for = 10
throttle-input-for = 30
screenchange-reload = false
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
pseudo-transparency = false

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/my-text-label]
type = custom/text
content = %{T7} 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/date]
type = internal/date
interval = 1.0
time = %k : %M
date = %b %e
format = <label>
format-foreground = ${color.white}
label = %date%  |  %time% 
label-font = 6

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/mpd]
type = internal/mpd
interval = 2
format-online = <label-song>
format-online-foreground = ${color.fg}
label-song = "%title%"
label-song-maxlen = 12
label-song-ellipsis = true
label-offline = "Offline"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Apps
 
[module/term]
type = custom/text
content = "%{T3}%{T-}"
content-foreground = ${color.black}
content-background = ${color.bg}
content-padding = 0
click-left  = termite &

[module/web]
type = custom/text
content = "%{T3}%{T-}"
content-foreground = ${color.white}
content-background = ${color.bg}
content-padding = 0
click-left  = firefox &

[module/files]
type = custom/text
content = "%{T3}%{T-}"
content-foreground = ${color.blue}
content-background = ${color.bg}
content-padding = 0
click-left  = thunar &

[module/edit]
type = custom/text
content = "%{T3}%{T-}"
content-foreground = ${color.blue-gray}
content-background = ${color.bg}
content-padding = 0
click-left  = geany &

[module/apps]
type = custom/text
content = "%{T3}%{T-}"
content-foreground = ${color.fg}
content-background = ${color.bg}
content-padding = 0
click-left  = ~/.config/polybar/scripts/launcher &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sep]
type = custom/text
content = " | "
content-font = 1
content-foreground = ${color.fg}

[module/sep2]
type = custom/text
content = "   "
content-foreground = ${color.fg}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/alsa]
type = internal/alsa
format-volume = <ramp-volume>
format-muted = <label-muted>
label-muted = %{A3:pavucontrol &:} 婢 %{A}
label-muted-foreground = ${color.gray}
ramp-volume-0 = %{A3:pavucontrol &:} 奄%{A}
ramp-volume-1 = %{A3:pavucontrol &:} 奔%{A}
ramp-volume-2 = %{A3:pavucontrol &:} 奔%{A}
ramp-volume-3 = %{A3:pavucontrol &:} 墳%{A}
ramp-volume-4 = %{A3:pavucontrol &:} 墳%{A}
ramp-volume-foreground = ${color.white}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/battery]
type = internal/battery
full-at = 99
battery = BAT1
adapter = ACAD
poll-interval = 2
time-format = %H:%M
format-charging = <animation-charging>
format-discharging = <ramp-capacity>
format-full = <label-full>
format-full-foreground = ${color.white}
label-full = 

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 
ramp-capacity-foreground = ${color.white}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-5 = 
animation-charging-6 = 
animation-charging-7 = 
animation-charging-8 = 
animation-charging-9 = 
animation-charging-foreground = ${color.white}
animation-charging-framerate = 750

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/network]
type = internal/network
interface = wlp2s0
click-left = kcmshell5 kcm_networkmanagement
interval = 1.0
accumulate-stats = true
unknown-as-up = true
format-connected = <label-connected>
format-connected-foreground = ${color.white}
format-disconnected = <label-disconnected>
format-disconnected-foreground = ${color.gray}
label-connected = 直
label-disconnected = 睊

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sysmenu]
type = custom/text
content = 
click-left = ~/.config/polybar/scripts/powermenu_alt

[module/ethernet_status]
type = custom/script
interval = 2
exec = ~/.config/scripts/ethernet_status.sh

[module/vpn_status]
type = custom/script
interval = 2
exec = ~/.config/scripts/vpn_bar.sh

[module/target_status]
type = custom/script
interval = 2
exec = ~/.config/scripts/target_status.sh

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
